services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    restart: unless-stopped

  perplexica:
    build:
      context: .
      dockerfile: Dockerfile
    image: itzcrazykns1337/perplexica
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 4080:3001
    volumes:
      - dbstore:/app/data
      - uploads:/app/uploads
      - ./config.toml:/app/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

volumes:
  dbstore:
  uploads:
